apiVersion: apps/v1
kind: Deployment
metadata:
  name: dept-dev
  namespace: ns-dev
spec:
  selector:
    matchLabels:
      app: dept-dev
  replicas: 2 # tells deployment to run 2 pods matching the template
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: dept-dev
    spec:
      containers:
      - name: dept-dev
        image: 887870046594.dkr.ecr.us-east-2.amazonaws.com/devecr:number
        resources:
          requests:
            memory: "128Mi"
            cpu: 100m
          limits:
            memory: "256Mi"
            cpu: 1
        ports:
        - containerPort: 80
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
             matchExpressions:
             - key: zone
               operator: In
               values:
               - us-east-2a
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
