apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-device-pvc
  namespace: ns-dev
spec:
  storageClassName: local-device
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi